name = input("Ввести ім'я: ")
surname = input("Ввести прізвище: ")
age = input("Ввести вік: ")
address = input("Ввести адресу ароживання: ")
phone_number = input("Ввести номер мобільного телефона: ")
email = input("Ввести ел. адресу: ")
print("Ім'я:", name)
print("Прізвище:", surname)
print("Вік:", age)
print("Адреса:", address)
print("Номер мобільного телефона:", phone_number)
print("Email:", email)