a = float(input("Введіть перше число: "))
b = float(input("Введіть друге число: "))
c = float(input("Введіть третє число: "))
d = float(input("Введіть четверте число: "))
result = (a+b)/(c+d)
print(f"Результат операції: {result:.2f}")